# Generated by Django 4.2.7 on 2025-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the file')),
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX'), ('Image', 'Image'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
    ]
