# Generated by Django 4.2.7 on 2025-12-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='file_date',
            field=models.DateField(blank=True, help_text='Date associated with the file', null=True),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='letter_reference_number',
            field=models.CharField(blank=True, help_text='Letter or reference number', max_length=255, null=True),
        ),
    ]
